config/routes.rb
Rails.application.routes.draw do
    resources :currencies
    resources :users, except: :index
    resources :wallets, except: [:edit, :update]
    resources :trades, except: [:show, :edit, :update] 
    get "/login", to: "sessions#new", as: "login"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/currency.rb
class Currency < ApplicationRecord
    has_many :wallets
    has_many :trades, through: :wallets
    has_many :users, through: :wallets
    has_one_attached :image
end

app/models/trade.rb
class Trade < ApplicationRecord
    belongs_to :offered_wallet, class_name: "Wallet", foreign_key: "offered_wallet_id"
    belongs_to :requested_wallet, class_name: "Wallet", foreign_key: "requested_wallet_id"
    
    def offered_currency
      self.offered_wallet.currency
    end
    
    def requested_currency
      self.requested_wallet.currency
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :wallets, dependent: :destroy
    has_many :currencies, through: :wallets
    has_many :trades, through: :wallets
    has_secure_password
    validates :username, uniqueness: true
end

app/models/wallet.rb
class Wallet < ApplicationRecord
    belongs_to :user
    belongs_to :currency
    has_many :trades, foreign_key: "offered_wallet_id", dependent: :destroy
    
    def currency_symbol
      self.currency.symbol
    end
    
    def credit(amount)
      self.amount -= amount
      self.save
    end
    
    def debit(amount)
      self.amount += amount
      self.save
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :get_current_user, :logged_in?
    # protect_from_forgery prepend: true, with: :exception
    # 
    # protected

    def get_current_user
        if @current_user
            return @current_user
        else
            @current_user = User.find_by(id: session[:user_id])
        end
    end

    def admin?
        user = get_current_user
        if user
            return user.admin
        end
    end

    def logged_in?
        !!get_current_user
    end

    def authorized
        redirect_to login_path unless logged_in?
    end
    
    def authorized_admin
        redirect_to login_path unless admin?
    end
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
    before_action :find_currency, only: [:show, :edit, :update, :destroy]
    before_action :authorized_admin, except: [:index, :show]
    
    def index
        @currencies = Currency.all
    end
    
    def show
    end
    
    def new
        @currency = Currency.new
    end
    
    def create
        @currency = Currency.new(
            currency_params(:name, :symbol)
        )
        if @currency.valid?
            @currency.save
            @currency.image.attach(params[:currency][:image])
            redirect_to @currency
        else
            render :new
        end
    end
    
    def edit
    end
    
    def update
        if @currency.valid?
            @currency.update(
                currency_params(:name, :symbol, :image)
                #added image to params here...
            )
            redirect_to @currency
        else
            render :edit
        end
    end
    
    def destroy
        @currency.destroy
        redirect_to currencies_path
    end
    
    private
    
        def find_currency
            @currency = Currency.find(params[:id])
        end
    
        def currency_params(*args)
            params.require(:currency).permit(*args)
        end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end
  
    def create
        @user = User.find_by(username: params[:username])
    
        if @user
          session["user_id"] = @user.id
          redirect_to @user
        else
          render :new
        end
    end
    
    def destroy
      session.clear
      redirect_to login_path
    end
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
    before_action :find_trade, only: [:show, :destroy]
    before_action :authorized, except: [:index, :show]
    
    def index
        @trades = Trade.all
    end
    
    def show
    end
    
    def new
        @trade = Trade.new
        @user = get_current_user
    end
    
    def create
        @trade = Trade.new(
            trade_params(:offered_amount, :offered_wallet_id, :requested_amount, :requested_wallet_id)
        )
        if @trade.valid?
            @trade.completed = false
            offered_amount = @trade.offered_amount
             @trade.offered_wallet.credit(offered_amount)
            @trade.save
            matching_trade?
            redirect_to trades_path
        else
            render :new
        end
    end
    
    def destroy
        if get_current_user.trades.include?(@trade)
            refund = @trade.offered_amount
            @trade.offered_wallet.debit(refund)
            @trade.destroy
            redirect_to trades_path
            return
        else 
            redirect_to login_path
            return
        end
    end
    
    private
    
        def find_trade
            @trade = Trade.find(params[:id])
        end
    
        def trade_params(*args)
            params.require(:trade).permit(*args)
        end
        
        def matching_trade?
          Trade.all.each do |t|
            if !t.completed && match?(t, @trade)
              t.requested_wallet.debit(@trade.offered_amount)
              @trade.requested_wallet.debit(t.offered_amount)
              t.completed = true
              @trade.completed = true
              t.save
              @trade.save
            else
              nil
            end
          end
        end
        
        def match?(trade, new_trade)
          new_trade.offered_currency == trade.requested_currency && new_trade.offered_amount >= trade.requested_amount && new_trade.requested_currency == trade.offered_currency &&
          new_trade.requested_amount == trade.offered_amount
        end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :find_user, only: [:show, :edit, :update, :destroy]
    before_action :authorized, except: [:new, :create]
    
    def show
    end
    
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(
            user_params(:name, :username, :password)
        )
        @user.admin = false
        if @user.valid?
            @user.save
            redirect_to @user
        else
            render :new
        end
    end
    
    def edit
    end
    
    def update
        if @user.valid?
            @user.update(
                user_params(:name, :username, :password)
            )
            redirect_to @user
        else
            render :edit
        end
    end
    
    def destroy
        @user.destroy
        redirect_to login_path
    end
    
    private
    
        def find_user
            @user = get_current_user
        end
    
        def user_params(*args)
            params.require(:user).permit(*args)
        end
    
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
    before_action :find_wallet, only: [:show, :destroy]
    before_action :authorized

    def index
        @wallets = get_current_user.wallets
    end
    
    def show
    end
    
    def new
        @wallet = Wallet.new
    end
    
    def create
        @user = get_current_user
        @wallet = Wallet.new(
            wallet_params(:currency_id, :amount)
        )
        @wallet.user = @user
        if @wallet.valid?
            @wallet.save
            redirect_to @wallet
        else
            render :new
        end
    end
    
    def destroy
        @wallet.destroy
        redirect_to wallets_path
    end
    
    private
    
        def find_wallet
            @wallet = Wallet.find(params[:id])
            if get_current_user.wallets.include?(@wallet)
                @wallet
            else
                @wallet = nil
                redirect_to login_path
            end
        end
    
        def wallet_params(*args)
            params.require(:wallet).permit(*args)
        end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/views/currencies/_currency_form.html.erb
<style> .form-group { margin-top: 2rem; }</style>

<%= form_for @currency do |f| %>
<div class="form-group">
    <%= f.label :name, "Currency Name:" %>
    <%= f.text_field :name %>
</div>
<div class="form-group">
    <%= f.label :symbol, "Abbreviation" %>
    <%= f.text_field :symbol %>
</div>
<div class="form-group">
    <%= f.label :image, "Add Image" %>
    <%= f.file_field(:image) %>
</div>
    <%= f.submit(class: "btn btn-primary")%>
<% end %>

app/views/currencies/edit.html.erb
<h1>Edit This Currency</h1>
<%= render partial: "shared/error_list", locals: {object: @currency} %>
<%= render "currency_form" %>

app/views/currencies/index.html.erb
<h1>Currencies</h1>

<% @currencies.each_with_index do |currency, index| %>
    <% if (index + 1) % 2 != 0 %>
        <div class="row">
    <% end %>
        <div class="col">
            <div class="card " style="width: 100%;">
                <% if currency.image.attached? %>
                    <%= image_tag currency.image, class: "card-img-top", style: "height: 8rem; padding-top: 1rem; padding-bottom: 1rem;" %>
                <% end %>
                <div class="card-body">
                    <%= link_to "#{currency.name} (#{currency.symbol})", currency, class: "btn btn-primary d-flex justify-content-center" %>
                </div>
            </div>
        </div>
    <% if (index + 1) % 2 == 0 %>
        </div>
    <% end %>
<% end %>

app/views/currencies/new.html.erb
<h1>Add a Currency</h1>

<%= render partial: "shared/error_list", locals: {object: @currency} %>
<%= form_for @currency do |f| %>
    <%= f.label :name, "Currency Name:" %>
    <%= f.text_field :name %>
    <%= f.label :symbol, "Abbreviation" %>
    <%= f.text_field :symbol %>
    <%= f.label :image, "Add Image" %>
    <%= f.file_field(:image) %>
    <%= f.submit %>
    <script>
      let symbolT = document.getElementById("currency_symbol").value
      
      fetch(`https://api.coindesk.com/v1/bpi/currentprice/${symbolT}.json`)
        .then(res => res.json())
        .then(jsonData => currencyObj(jsonData))
      
    </script>
<% end %>

app/views/currencies/show.html.erb
<h1><%= @currency.name %> (<%= @currency.symbol %>)</h1>

<% if @currency.image.attached? %>
    <%= image_tag @currency.image, class: "rounded mx-auto d-block", style: "width: 6rem;" %>
<% end %>

<div id="symbol" style="color: white;"><%= @currency.symbol%>
</div>

<div id="usd-container" class="d-flex justify-content-center">USD: $</div>

<div id="rate-container" class="d-flex justify-content-center">Rate: ฿</div>

  <script type="text/javascript">
    document.addEventListener('DOMContentLoaded',function(){
      let symbolT = document.getElementById("symbol").innerText
      apiFetch(symbolT)
    })

//fetches the target currency
    function apiFetch(symbolT){
      fetch(`https://api.coindesk.com/v1/bpi/currentprice/${symbolT}.json`)
        .then(res => res.json())
        .then(jsonData => currencyObj(jsonData,symbolT))
    }  

    function currencyObj(jsonData,symbolT){
      let usdRateFloat = jsonData.bpi.USD.rate_float
      let targetRateFloat = jsonData.bpi[symbolT].rate_float
      
      let apiTargetContainer = document.getElementById("rate-container")
      let apiTargetDiv = document.createElement("div")
      let targetRate = jsonData.bpi[symbolT].rate
        apiTargetDiv.innerText = targetRate
        apiTargetContainer.appendChild(apiTargetDiv)
      
      let apiUsdContainer = document.getElementById("usd-container")
      let apiUsdDiv = document.createElement("div")
      let usdRate = jsonData.bpi.USD.rate
      // debugger
      let usdConversion = Number(targetRateFloat/usdRateFloat).toFixed(5)
        apiUsdDiv.innerText = usdConversion
        apiUsdContainer.appendChild(apiUsdDiv) 
        
      window.setTimeout(function(){location.reload(true)}, 3000);
    };
  </script>


<% if logged_in? && get_current_user.admin? %>
    <%= form_tag "#{@currency.id}/edit", method: "get" do %>
        <%= submit_tag "Edit This Currency", class: "btn btn-primary" %>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlEx</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color: silver;">
   <div class="container rounded-bottom" style="background-color: white; padding-bottom: 1rem">
    <nav class="navbar navbar-light rounded-bottom" style="background-color: #d8dee9; margin-bottom: 1rem;">
        <span>
            <%= link_to "Currencies", currencies_path %>
            <%= link_to "Trades", trades_path %>
        </span>
        <span>
            <% if get_current_user %>
                Welcome, <%= get_current_user.name %>!
                <%= link_to "Profile", get_current_user %>
                <%= link_to "Wallets", wallets_path %>
                <%= link_to "Logout", logout_path, method: "DELETE" %>
            <% else %>
                <%= link_to "Login", login_path %>
            <% end %>
        </span>
    </nav>
      <article>
        <%= yield %>
      </article>
   </div>
  </body>
</html>

app/views/shared/_delete_button.html.erb
<%= form_tag object, method: "delete" do %>
    <%= submit_tag "Delete This #{object.class}", class: "btn btn-danger" %>
<% end %>

app/views/shared/_error_list.html.erb
<% if object.errors %>
    <ul class="error-list">
        <% object.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
    </ul>
<% end %>

app/views/trades/_make_trade_button.html.erb
<div class="d-flex justify-content-center">
<%= form_tag new_trade_path, method: "get" do %>
    <%= submit_tag "Make a Trade", class: "btn btn-success"%>
<% end %>
</div>

app/views/trades/index.html.erb
<h1>Pending Trades</h1>

<div id="carouselConrols" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        <% index = 0 %>
        <% @trades.each do |trade| %>
            <% unless trade.completed %>
            <% if index == 0 %>
                <div class="carousel-item active" data-interval="5000">
                <% index += 1 %>
            <% else %>
                <div class="carousel-item" data-interval="5000">
            <% end %>
                <% if trade.offered_currency.image.attached? %>
                    <%= image_tag trade.offered_currency.image, class: "d-block w-100", style: "height: 8rem; margin-bottom: 10rem;" %>
                <% end %>
                    <div class="carousel-caption d-none d-md-block" >
                        <h2 style="color: black;"><%= trade.offered_amount %> <%= trade.offered_currency.symbol %> for <%= trade.requested_amount %> <%= trade.requested_currency.symbol %></h2>
                    </div>
                </div>
            <% end %>
        <% end %>
    </div>
</div>

        <%= render "make_trade_button" %>

app/views/trades/new.html.erb
<style> .form-group { margin-top: 2rem; }</style>
<h1>Make a Trade</h1>

<%= render partial: "shared/error_list", locals: {object: @trade} %>

<%= form_for @trade do |f| %>
<div class="form-group">
    <%= f.label :offered_amount, "Offer:" %>
    <%= f.number_field :offered_amount %>
    <%= f.collection_select(:offered_wallet_id, @user.wallets, :id, :currency_symbol, prompt: "Currency") %>
</div>
<div class="form-group">
    <%= f.label :requested_amount, "Request:" %>
    <%= f.number_field :requested_amount %>
    <%= f.collection_select(:requested_wallet_id, @user.wallets, :id, :currency_symbol, prompt: "Currency") %>
</div>
    <%= f.submit(class: "btn btn-success") %>
<% end %>

app/views/trades/show.html.erb
<h1>Detail View</h1>
<% if @trade.offered_currency.image.attached? %>
    <%= image_tag @trade.offered_currency.image %>
<% end %>
<h2><%= @trade.offered_amount %> <%= @trade.offered_currency.symbol %> for <%= @trade.requested_amount %> <%= @trade.requested_currency.symbol %></h2>

<%= render "make_trade_button" %>

app/views/users/_user_form.html.erb
<style> .form-group { margin-top: 2rem; }</style>

<%= form_for @user do |f| %>
<div class="form-group">
    <%= f.label :name, "Full Name:" %>
    <%= f.text_field :name %>
</div>
<div class="form-group">
    <%= f.label :username, "Username:" %>
    <%= f.text_field :username %>
</div>
<div class="form-group">
    <%= f.label :password, "Password:" %>
    <%= f.password_field :password %>
</div>
    <%= f.submit(class: "btn btn-primary")%>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Your Profile</h1>

<%= render partial: "shared/error_list", locals: {object: @user} %>
<%= render "user_form" %>

<div class="form-group">
<%= form_tag @user, method: "delete" do %>
    <%= submit_tag "Delete Your account", class: "btn btn-danger"%>
<% end %>
</div>

app/views/users/new.html.erb
<h1> Create Account or <%= link_to "Login", login_path %></h1>

<%= render partial: "shared/error_list", locals: {object: @user} %>

<%= render "user_form" %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<% unless @user.trades.empty? %>
<h2>Your Trades:</h2>
<ul>
    <% @user.trades.each do |trade|%>
        <li>
            <%= trade.offered_amount %> <%= trade.offered_currency.symbol %> for <%= trade.requested_amount %> <%= trade.requested_currency.symbol %> 
            <div style="display: inline-block;">
            <%= render partial: "shared/delete_button", locals: {object: trade} %>
            </div>
        </li>
    <% end %>
</ul>
<% end %>
<div class="form-group">
<%= form_tag "#{@user.id}/edit", method: "get" do %>
    <%= submit_tag "Edit Your Profile", class: "btn btn-primary"%>
<% end %>
</div>

<% if @user.admin? %>
    <%= form_tag new_currency_path, method: "get" do %>
        <%= submit_tag "Add a New Currency", class: "btn btn-success" %>
    <% end %>
<% end %>

app/views/wallets/_add_wallet_button.html.erb
<%= form_tag new_wallet_path, method: "get" do %>
    <%= submit_tag "Add a New Wallet", class: "btn btn-success" %>
<% end %>

app/views/wallets/index.html.erb
<h1>Your Wallets</h1>
<% if get_current_user %>
    <ul>
        <% @wallets.each do |wallet| %>
            <li><%= link_to "#{wallet.currency.symbol}", wallet %></li>
        <% end %>
    </ul>
<% end %>

<%= render "add_wallet_button" %>

app/views/wallets/new.html.erb
<style> .form-group { margin-top: 2rem; }</style>
<h1>Deposit Funds</h1>

<%= render partial: "shared/error_list", locals: {object: @wallet} %>


<%= form_for @wallet do |f| %>
<div class="form-group">
    <%= f.label :amount, "Amount to Deposit:" %>
    <%= f.number_field :amount %>
</div>
<div class="form-group">
    <%= f.label :currency_id %>
    <%= f.collection_select(:currency_id, Currency.all, :id, :symbol, prompt: "Currency") %>
</div>
    <%= f.submit(class: "btn btn-primary") %>
<% end %>

app/views/wallets/show.html.erb
<h1><%= @wallet.user.name %>'s <%= @wallet.currency.name %> Wallet</h1>
<% if @wallet.currency.image.attached? %>
    <div class="d-flex justify-content-center">
        <%= image_tag @wallet.currency.image, style: "height: 8rem;"%>
    </div>
<% end %>

<div id="symbol" style="color: white;"><%= @wallet.currency.symbol%>
</div>

<div id="usd-container" class="d-flex justify-content-center">USD: $</div>

<div id="rate-container" class="d-flex justify-content-center">Rate: ฿</div>

  <script type="text/javascript">
    document.addEventListener('DOMContentLoaded',function(){
      let symbolT = document.getElementById("symbol").innerText
      apiFetch(symbolT)
    })

//fetches the target currency
    function apiFetch(symbolT){
      fetch(`https://api.coindesk.com/v1/bpi/currentprice/${symbolT}.json`)
        .then(res => res.json())
        .then(jsonData => currencyObj(jsonData,symbolT))
    }  

    function currencyObj(jsonData,symbolT){
      let usdRateFloat = jsonData.bpi.USD.rate_float
      let targetRateFloat = jsonData.bpi[symbolT].rate_float
      
      let apiTargetContainer = document.getElementById("rate-container")
      let apiTargetDiv = document.createElement("div")
      let targetRate = jsonData.bpi[symbolT].rate
        apiTargetDiv.innerText = targetRate
        apiTargetContainer.appendChild(apiTargetDiv)
      
      let apiUsdContainer = document.getElementById("usd-container")
      let apiUsdDiv = document.createElement("div")
      let usdRate = jsonData.bpi.USD.rate
      // debugger
      let usdConversion = Number(targetRateFloat/usdRateFloat).toFixed(5)
        apiUsdDiv.innerText = usdConversion
        apiUsdContainer.appendChild(apiUsdDiv) 
      window.setTimeout(function(){location.reload(true)}, 3000);
    };
  </script>
  
<h2>Current Balance:</h2>
<p><%= @wallet.amount %> <%= link_to @wallet.currency.symbol, @wallet.currency %></p>

<% unless @wallet.trades.empty? %>
<h2>Pending Trades From This Wallet:</h2>
<ul>
    <% @wallet.trades.each do |trade|%>
        <li>
            <%= trade.offered_amount %> <%= trade.offered_currency.symbol %> for <%= trade.requested_amount %> <%= trade.requested_currency.symbol %> 
            <div style="display: inline-block;">
            <%= render partial: "shared/delete_button", locals: {object: trade} %>
            </div>
        </li>
    <% end %>
</ul>
<% end %>
<%= render partial: "shared/delete_button", locals: {object: @wallet} %>